### ISSUE TITLE
Timur TODO after 15.01.2024

### ISSUE THREAD

**Issue by NasyrovTimur** [timattt/TypeSix#2]
- [ ] Макет сайта
- [x] интеграция с другими вузами
(сарафанка)
- [ ] найти фронта
- [ ] подумать над названием домена
- [ ] опросить людей насчет названия домена
- [ ] сделать презу для продукта
- [x] написать список хобби, сообществ, спорта и тд
- [x] подумать нам метрикой
(малоранговая аппроксимация, свд разложение)
- [ ] защита перс данных
